services:
  postgres:
    image: postgres:14
    container_name: finance_db
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance_network

  mageai:
    image: mageai/mageai:latest
    container_name: finance_mage
    command: mage start default_repo
    environment:
      POSTGRES_DBNAME: finance_db
      POSTGRES_SCHEMA: public
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
      POSTGRES_HOST: postgres
    ports:
      - "6789:6789"
    volumes:
      - ./mage_data:/root/.mage_data
    depends_on:
      - postgres
    networks:
      - finance_network

networks:
  finance_network:
    name: finance_network
    driver: bridge

volumes:
  postgres_data:
  mage_data: